language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
  - extra-android-support
  - extra-android-m2repository
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew build test || ./gradlew testDebug'
deploy:
- provider: releases
  api_key:
    secure: dy25Z+PzdZaw8HPq8/Ob0ao72yTmTmq+0wbowc/TKBQ5MN786pGckguyJx5yTLo8NAlDyY08e+TNOtp4rnftJne1xYlDxIkSfA79yv1AkUvGGFJHglQh7ExAsZGIRBtoNbS2lbcC/tUeaE0l2iEVjaq6vLATaZ73aKK5Ut9Keh8=
  file_glob: true
  file: "./enabler/build/outputs/apk/enabler-release-*.*.*.apk"
  on:
    repo: openxc/openxc-android
    tags: true
- provider: script
  script: scripts/deploy.sh
  on:
    repo: openxc/openxc-android
    tags: true
env:
  global:
  - secure: dmvaay5GzUO1qkaRk46+o96rRmP4cKAvbgD6njgCegfaGbXwDAMQGKjPeJc5uORWpmxnqpqSg8+0ZvYwkUsflvG3tTtsPV+llzjkDGnstvLxFBEU/JibLoUscOdrdkrc6DsxZtfZ9jJWkb271ARjgTxjMHnNcN3jwTLfU67htXc=
  - secure: Kr9rh1Y7MM1iJ6hS0YO/1ymLfHt+ncsMk4nY2DEO74V2ROTaqWsA1GdtczWb8AD3ZjeF8Qw+wBlaJvZ5Sx51ydGnmT5X/e/pHkKMIe96UHjugvogEigLcw6pI9ZRo/p8A+tZ3WOeY2VVoQhOx6sCObNBIEQE5NVrRpldrTB+D+M=
  - secure: eBbtEJOTUJ3PaM1xfgW9ccXdiG28TeMGYWfxCW1nBQvtdLzIHyfDZb8FNEFkChaq41sk44+IVMQNLj8tybAPlg3E6SOwLd5SWjhv+0f+tJWYBY1j04MKS8WE3osE3iifs+CafjOk8lws4YH0tKaUXsqqLO/53OuT3px2mlSxjwc=
  - secure: axhDzPFk7DxUc1kUDRe9s7DD8PPByRiUNat2SssxgLweT30jgQJaOrjLssmJrjb0ZhIJQrVEXiRKYUmfo+9uNY3sT71lWRFv89fVHg5P2fg2LMX2nJEuSOXIIafb3VH8gFE01vdGXzQnZ+uNJPnOjejzI59JTPBtpki5zh03nYU=
  - secure: dB950vdO3N6GSagrqmAFsTZYaRd2B6IcCZuYTqiI0WS9hQFxrka53gNVblAWcfSsRpyGdsoRzK1LdKgZcFm2YBVPXriiM/CNWfolWMxii7aY/BQs03tUsafcwaprgpDlJqeCIbG2nD6/Yk2g48JEjEQz/a1QI2Ppw/FLNe26jc4=
  - secure: fSxLsuELLvaNmGtFn4ZtELt8d1gSJZwJ+5+QahpV0b9Nf/JNUehSl4RSYVFsq2uw5fuhdsgy/OujpGEYWTA6iDidaB+YOXfwR3q1vpxwUCIEAjbhVG0TwlFh0wqcYOq8FHUBlSNh9DoLJh61N+Y1pCzoXAPFBqaqQ1wjUpxUfCw=
  - secure: VHn45y17v68I/VNhIBCNue9eRMdaRurHBSu8cGO3NLcjZFpJqYehqKnwhjIS2eP1SDHEM++LFz6XpANpU4KwdjnYaP5qEU4b2zEVqvc+9GZK37kFIaeSaOrvoRGYVrzp+oeU8ehG6MjsgXWjIwE4QNLVc8dinILjuqWXY5zxqGs=
  - GRADLE_OPTS="-Xmx1024m -XX:MaxPermSize=1024m"
